import AppKit
import Combine
import Foundation

// MARK: - Pure planning (testable — NOT gated to macOS 26)

/// Decisions for the on-device gap-filler, kept free of I/O so they can be tested.
enum GapFillPlanner {
    /// `Briefing Status` value marking a page as an on-device draft. The cloud routine
    /// and the intraday skill treat it as "not briefed": if Claude runs with credit it
    /// rewrites the page in place and sets the status back to `Auto`.
    static let onDeviceStatus = "On-device"

    /// Look-ahead horizon: end of tomorrow. Claude credit can run out before the
    /// 02:04 cloud run, so tomorrow's meetings get a draft the evening before.
    static func horizon(from now: Date, calendar: Calendar = .current) -> Date {
        let startOfToday = calendar.startOfDay(for: now)
        return calendar.date(byAdding: .day, value: 2, to: startOfToday) ?? now.addingTimeInterval(48 * 3600)
    }

    /// One key per occurrence, so a moved meeting is re-checked at its new time.
    static func key(_ e: MeetingEvent) -> String {
        "\(e.id)|\(Int(e.startDate.timeIntervalSince1970))"
    }

    /// Meetings starting after `now` and before `until` that haven't been handled.
    /// Skips all-day events, ad-hoc meetings and anything with no attendees (focus
    /// blocks and personal holds don't need a brief).
    static func candidates(_ events: [MeetingEvent], now: Date, until: Date,
                           handled: Set<String>) -> [MeetingEvent] {
        events
            .filter { e in
                !e.isAllDay
                    && !e.id.hasPrefix("adhoc-")
                    && e.startDate > now
                    && e.startDate < until
                    && !(e.attendees ?? []).isEmpty
                    && !handled.contains(key(e))
            }
            .sorted { $0.startDate < $1.startDate }
    }

    /// True when any brief title in the event's ±12h window is a close enough match.
    /// Same Levenshtein similarity and default threshold as the brief panel, so a
    /// brief the panel would show counts as "already briefed".
    static func hasBrief(titles: [String], for title: String, threshold: Double = 0.6) -> Bool {
        let wanted = title.lowercased()
        return titles.contains { PreCallBriefService.similarity($0.lowercased(), wanted) >= threshold }
    }

    /// Notion blocks for the page body. The callout up top makes the provenance
    /// obvious: this is a low-fidelity stand-in, not a Claude briefing.
    static func pageBlocks(summary: String, talkingPoints: [String], prepActions: [String],
                           usedTeams: Bool, usedPriorNotes: Bool) -> [[String: Any]] {
        func rich(_ s: String) -> [[String: Any]] {
            [["type": "text", "text": ["content": String(s.prefix(1900))]]]
        }
        func clean(_ items: [String]) -> [String] {
            items.map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }.filter { !$0.isEmpty }.prefix(3).map { $0 }
        }
        var sources = ["calendar invite"]
        if usedPriorNotes { sources.append("prior meeting notes") }
        if usedTeams { sources.append("Teams chat") }

        var blocks: [[String: Any]] = [[
            "object": "block", "type": "callout",
            "callout": [
                "rich_text": rich("On-device draft (Apple Intelligence). No Claude briefing existed, so this was generated locally from: \(sources.joined(separator: ", ")). Lower quality, so check before relying on it. Claude replaces this page if it runs with credit."),
                "icon": ["type": "emoji", "emoji": "🤖"],
                "color": "gray_background",
            ],
        ]]
        func heading(_ s: String) {
            blocks.append(["object": "block", "type": "heading_3", "heading_3": ["rich_text": rich(s)]])
        }
        heading("Summary")
        blocks.append(["object": "block", "type": "paragraph", "paragraph": ["rich_text": rich(summary)]])
        let points = clean(talkingPoints)
        if !points.isEmpty {
            heading("Talking points")
            blocks += points.map { ["object": "block", "type": "bulleted_list_item",
                                    "bulleted_list_item": ["rich_text": rich($0)]] }
        }
        let actions = clean(prepActions)
        if !actions.isEmpty {
            heading("Prep")
            blocks += actions.map { ["object": "block", "type": "to_do",
                                     "to_do": ["rich_text": rich($0), "checked": false]] }
        }
        return blocks
    }
}

// MARK: - Service

/// Makes sure every meeting has *some* Pre-Call Briefing. Every 5 minutes it looks at
/// meetings from now to the end of tomorrow; any with no brief in Notion gets one
/// generated by the on-device Foundation Models system model, fed the invite, the
/// most recent prior Meeting Notes, and the Teams chat context the teams-chat-mcp
/// feeder writes onto the Calendar Events row. Off by default; needs macOS 26 and
/// the Notion token.
@MainActor
final class OnDeviceBriefGapFiller: ObservableObject {
    enum Keys {
        static let enabled = "onDeviceBriefGapFillEnabled"
        static let handled = "onDeviceBriefGapFillHandled"
        static let lastResult = "onDeviceBriefGapFillLastResult"
    }

    @Published private(set) var lastResult: String = UserDefaults.standard.string(forKey: Keys.lastResult) ?? ""

    var isEnabled: Bool {
        get { UserDefaults.standard.bool(forKey: Keys.enabled) }
        set {
            UserDefaults.standard.set(newValue, forKey: Keys.enabled)
            objectWillChange.send()
            reconfigure()
        }
    }

    static var isSupported: Bool {
        if #available(macOS 26.0, *) { return true }
        return false
    }

    private weak var calendarService: CalendarService?
    private let enrichment: CalendarEnrichmentService
    private var timer: Timer?
    private var wakeObserver: NSObjectProtocol?
    private var isRunning = false
    private var handledOrder: [String]
    private var handled: Set<String>

    private let logPath: String = {
        let dir = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Library/Logs/MeetingReminder", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir.appendingPathComponent("ondevice-brief-gapfill.log").path
    }()
    private lazy var logger = CalendarSyncLogger(path: logPath)

    init(calendarService: CalendarService, enrichment: CalendarEnrichmentService) {
        self.calendarService = calendarService
        self.enrichment = enrichment
        let saved = UserDefaults.standard.stringArray(forKey: Keys.handled) ?? []
        handledOrder = saved
        handled = Set(saved)
    }

    func start() { reconfigure() }

    private func reconfigure() {
        timer?.invalidate()
        timer = nil
        if let wakeObserver { NSWorkspace.shared.notificationCenter.removeObserver(wakeObserver) }
        wakeObserver = nil
        guard isEnabled, Self.isSupported else { return }

        timer = Timer.scheduledTimer(withTimeInterval: 300, repeats: true) { [weak self] _ in
            Task { @MainActor in await self?.tick() }
        }
        wakeObserver = NSWorkspace.shared.notificationCenter.addObserver(
            forName: NSWorkspace.didWakeNotification, object: nil, queue: .main
        ) { [weak self] _ in
            // Give the network and EventKit a moment after wake.
            Task { @MainActor in
                try? await Task.sleep(nanoseconds: 30_000_000_000)
                await self?.tick()
            }
        }
        logger.info("gap-filler started — briefing meetings with no brief, now → end of tomorrow")
        Task { await tick() }
    }

    /// One pass over the upcoming hour. Safe to call any time.
    func tick() async {
        guard isEnabled, !isRunning, let calendarService else { return }
        guard let token = KeychainHelper.read(key: CalendarSyncConstants.tokenKeychainKey), !token.isEmpty else { return }
        let now = Date()
        let horizon = GapFillPlanner.horizon(from: now)
        let due = GapFillPlanner.candidates(calendarService.upcomingEvents(until: horizon),
                                            now: now, until: horizon, handled: handled)
        guard !due.isEmpty else { return }

        isRunning = true
        defer { isRunning = false }
        let client = CalendarSyncNotionClient(token: token, logger: logger)
        let skipRules = (try? await CalendarSyncNotionQueries.fetchSkipRules(client: client)) ?? []

        for event in due {
            if SkipFilter.shouldSkip(title: event.title, rules: skipRules) {
                logger.info("skip-list: '\(event.title)'")
                markHandled(event)
                continue
            }
            await fill(event, client: client)
        }
    }

    // Internal (not private) so the opt-in live test can drive one real fill.
    func fill(_ event: MeetingEvent, client: CalendarSyncNotionClient) async {
        // A Notion error must never read as "no brief": that would duplicate one.
        guard let titles = await briefTitles(near: event, client: client) else {
            logger.warn("brief lookup failed for '\(event.title)' — retrying next tick")
            return
        }
        if GapFillPlanner.hasBrief(titles: titles, for: event.title) {
            logger.info("already briefed: '\(event.title)'")
            markHandled(event)
            return
        }
        guard #available(macOS 26.0, *) else { return }

        let row = await enrichment.fetchEnrichment(for: event)
        let priorNotes = await NotionPriorNotesReader.fetch(title: event.title, before: event.startDate,
                                                            logPath: logPath)
        let ctx = IntradayBriefContext.from(event, priorNotes: priorNotes, teamsContext: row?.teamsChatContext)

        let brief: GapFillBrief
        do {
            brief = try await FoundationModelsBriefService.generateGapFill(ctx)
        } catch {
            // Don't loop on a model that can't run (e.g. Apple Intelligence off).
            record("generation failed for '\(event.title)': \(error)")
            markHandled(event)
            return
        }

        // Claude may have written one while the model ran.
        if let again = await briefTitles(near: event, client: client),
           GapFillPlanner.hasBrief(titles: again, for: event.title) {
            logger.info("brief appeared during generation: '\(event.title)' — discarding draft")
            markHandled(event)
            return
        }

        let blocks = GapFillPlanner.pageBlocks(summary: brief.summary, talkingPoints: brief.talkingPoints,
                                               prepActions: brief.prepActions,
                                               usedTeams: ctx.teamsContext != nil,
                                               usedPriorNotes: priorNotes != nil)
        var properties: [String: Any] = [
            CalendarSyncConstants.preCallBriefingsTitleProperty: ["title": [["text": ["content": event.title]]]],
            CalendarSyncConstants.preCallBriefingsDateProperty: ["date": ["start": Self.iso(event.startDate),
                                                                          "end": Self.iso(event.endDate)]],
            "Attendees": ["rich_text": [["text": ["content": String((event.attendees ?? []).joined(separator: ", ").prefix(1900))]]]],
            // The Claude runners treat "On-device" as not-yet-briefed and rewrite the page.
            "Briefing Status": ["select": ["name": GapFillPlanner.onDeviceStatus]],
        ]
        if let rowID = row?.rowPageID {
            properties["Calendar Event"] = ["relation": [["id": rowID]]]
        }
        do {
            let resp = try await client.post(path: "/pages", body: [
                "parent": ["type": "data_source_id", "data_source_id": CalendarSyncConstants.preCallBriefingsDataSourceID],
                "properties": properties,
                "children": blocks,
            ], idempotent: false)
            markHandled(event)
            let url = resp["url"] as? String ?? "?"
            record("briefed '\(event.title)' on-device (teams=\(ctx.teamsContext != nil) notes=\(priorNotes != nil)) → \(url)")
            NotificationService.shared.postInfo(
                id: "ondevice-gapfill-\(event.id)",
                title: "🤖 On-device briefing added",
                body: "“\(event.title)” had no briefing, so a local draft is in Notion.")
        } catch {
            // Not marked: the next tick's lookup sees a create that actually landed.
            record("Notion create failed for '\(event.title)': \(error)")
        }
    }

    /// Titles of Pre-Call Briefings dated within ±12h of the event; nil on any error.
    private func briefTitles(near event: MeetingEvent, client: CalendarSyncNotionClient) async -> [String]? {
        let date = CalendarSyncConstants.preCallBriefingsDateProperty
        let body: [String: Any] = [
            "page_size": 100,
            "filter": ["and": [
                ["property": date, "date": ["on_or_after": Self.iso(event.startDate.addingTimeInterval(-12 * 3600))]],
                ["property": date, "date": ["on_or_before": Self.iso(event.startDate.addingTimeInterval(12 * 3600))]],
            ]],
        ]
        do {
            let resp = try await client.post(
                path: "/data_sources/\(CalendarSyncConstants.preCallBriefingsDataSourceID)/query", body: body)
            let rows = resp["results"] as? [[String: Any]] ?? []
            return rows.compactMap { row in
                let props = row["properties"] as? [String: Any]
                let title = (props?[CalendarSyncConstants.preCallBriefingsTitleProperty] as? [String: Any])?["title"] as? [[String: Any]]
                let text = title?.compactMap { $0["plain_text"] as? String }.joined() ?? ""
                return text.isEmpty ? nil : text
            }
        } catch {
            return nil
        }
    }

    private func markHandled(_ event: MeetingEvent) {
        let key = GapFillPlanner.key(event)
        guard handled.insert(key).inserted else { return }
        handledOrder.append(key)
        while handledOrder.count > 300 { handled.remove(handledOrder.removeFirst()) }
        UserDefaults.standard.set(handledOrder, forKey: Keys.handled)
    }

    private func record(_ message: String) {
        logger.info(message)
        lastResult = message
        UserDefaults.standard.set(message, forKey: Keys.lastResult)
    }

    private static func iso(_ d: Date) -> String {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f.string(from: d)
    }
}
